/*CÂU 1*/
CREATE FUNCTION fNHANVIEN_Age (@MaNV nvarchar(9))
RETURNS INT
AS 
BEGIN 
RETURN (
	SELECT DATEDIFF(year, NGSINH, GETDATE()) + 1
	FROM NHANVIEN
	WHERE MANV = @MaNV
);
END
/*CÂU 1.2*/
GO
CREATE FUNCTION fNHANVIEN_TongSoDeAn (@MaNV nvarchar(9))
RETURNS INT
AS
BEGIN
RETURN (
	SELECT COUNT (mada)
	FROM PHANCONG
	WHERE MA_NVIEN = @MaNV
)
END
/*CÂU 1.3*/
GO
CREATE FUNCTION fMaNV_GioiTinh (@phai nvarchar(3))
RETURNS INT
BEGIN
RETURN (
	SELECT COUNT (MaNV)
	FROM NHANVIEN
	WHERE PHAI = @phai
)
END
/*CÂU 1.4*/
GO
CREATE FUNCTION fMaNV_LTB (@TenPhong nvarchar(30))
RETURNS INT
BEGIN
RETURN (
	SELECT AVG(b.luong) 
	FROM PHONGBAN a
	INNER JOIN NHANVIEN b ON a .MAPHG = b.PHG
	WHERE TENPHG LIKE '%' + @TenPhong + '%'
)
END
/*CÂU 1.5*/
GO
CREATE FUNCTION fN_ThongTinPhongDeAn (@MaPhg int)
RETURNS @LIST TABLE (TenPhong nvarchar(15), TenTruongPhong nvarchar(30), SoLuongDeAn int)
AS
BEGIN
	INSERT INTO @LIST
	SELECT a.TENPHG, b.HONV + ' ' + b.TENLOT + ' ' + B.TENNV, 
	(SELECT COUNT (c.MADA) FROM DEAN c WHERE c.PHONG = a.MAPHG)
	FROM PHONGBAN a
	INNER JOIN NHANVIEN b ON a.MAPHG = b.PHG;
	RETURN;
END
/*CÂU 2*/
GO
CREATE VIEW N_DD_NV AS 
SELECT HONV,TENNV,TENPHG,DIADIEM FROM PHONGBAN
INNER JOIN DIADIEM_PHG ON DIADIEM_PHG.MAPHG=PHONGBAN.MAPHG
INNER JOIN NHANVIEN ON NHANVIEN.PHG=PHONGBAN.MAPHG
SELECT * FROM N_DD_NV
/*CÂU 2.2*/
GO
CREATE VIEW N_TUOI_NV AS 
SELECT TENNV,LUONG,YEAR (GETDATE())-YEAR(NGSINH) AS 'TUỔI' FROM NHANVIEN
SELECT * FROM N_TUOI_NV